name: Build Dynalink DL-WRX36 Firmware
on:
  schedule:
    - cron: '30 3 * * *'
    - cron: '0 15 * * *'

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
             - name: Checkout
               uses: actions/checkout@v3
             - name: Build Firmware
               run: |
                wget https://downloads.openwrt.org/snapshots/targets/qualcommax/ipq807x/openwrt-imagebuilder-qualcommax-ipq807x.Linux-x86_64.tar.xz
                tar -xf openwrt-imagebuilder-qualcommax-ipq807x.Linux-x86_64.tar.xz
                wget https://downloads.openwrt.org/releases/packages-22.03/aarch64_cortex-a53/packages/collectd-mod-cpufreq_5.12.0-34_aarch64_cortex-a53.ipk -P openwrt-imagebuilder-qualcommax-ipq807x.Linux-x86_64/packages/
                mkdir -p openwrt-imagebuilder-qualcommax-ipq807x.Linux-x86_64/files/etc/config
                cp .github/workflows/dockerd openwrt-imagebuilder-qualcommax-ipq807x.Linux-x86_64/files/etc/config
                cd openwrt-imagebuilder-qualcommax-ipq807x.Linux-x86_64
                make image PROFILE=dynalink_dl-wrx36 FILES="files" PACKAGES="luci-app-pbr htop collectd-mod-cpufreq luci-app-openvpn openvpn-openssl openvpn-easy-rsa collectd-mod-conntrack collectd-mod-irq collectd-mod-thermal luci-app-ksmbd luci-proto-wireguard ath11k-firmware-ipq8074 base-files bash blkid block-mount blockd btrfs-progs busybox ca-bundle ca-certificates cgi-io collectd collectd-mod-cpu collectd-mod-interface collectd-mod-iwinfo collectd-mod-load collectd-mod-memory collectd-mod-network collectd-mod-rrdtool containerd -dnsmasq dnsmasq-full docker docker-compose dockerd dropbear e2fsprogs fdisk firewall4 fstools fwtool getrandom hostapd-common ip6tables-nft ipq-wifi-dynalink_dl-wrx36 iptables-mod-extra iptables-nft iw iwinfo jansson jshn jsonfilter kernel kmod-asn1-decoder kmod-asn1-encoder kmod-ath kmod-ath11k kmod-ath11k-ahb kmod-br-netfilter kmod-cfg80211 kmod-crypto-acompress kmod-crypto-aead kmod-crypto-authenc kmod-crypto-cbc kmod-crypto-ccm kmod-crypto-cmac kmod-crypto-crc32c kmod-crypto-ctr kmod-crypto-deflate kmod-crypto-des kmod-crypto-echainiv kmod-crypto-gcm kmod-crypto-gf128 kmod-crypto-ghash kmod-crypto-hash kmod-crypto-hmac kmod-crypto-manager kmod-crypto-md5 kmod-crypto-michael-mic kmod-crypto-null kmod-crypto-rng kmod-crypto-seqiv kmod-crypto-sha1 kmod-crypto-sha256 kmod-dax kmod-dm kmod-dummy kmod-fs-autofs4 kmod-fs-btrfs kmod-fs-exfat kmod-fs-ext4 kmod-fs-ntfs3 kmod-fuse kmod-gpio-button-hotplug kmod-hwmon-core kmod-ikconfig kmod-ip6tables kmod-ipsec kmod-ipt-conntrack kmod-ipt-core kmod-ipt-extra kmod-ipt-nat kmod-ipt-nat6 kmod-ipt-physdev kmod-iptunnel kmod-keys-encrypted kmod-keys-trusted kmod-leds-gpio kmod-lib-crc-ccitt kmod-lib-crc16 kmod-lib-crc32c kmod-lib-lzo kmod-lib-raid6 kmod-lib-textsearch kmod-lib-xor kmod-lib-zlib-deflate kmod-lib-zlib-inflate kmod-lib-zstd kmod-libphy kmod-mac80211 kmod-macvlan kmod-nf-conntrack kmod-nf-conntrack-netlink kmod-nf-conntrack6 kmod-nf-flow kmod-nf-ipt kmod-nf-ipt6 kmod-nf-ipvs kmod-nf-log kmod-nf-log6 kmod-nf-nat kmod-nf-nat6 kmod-nf-nathelper kmod-nf-nathelper-extra kmod-nf-reject kmod-nf-reject6 kmod-nfnetlink kmod-nft-compat kmod-nft-core kmod-nft-fib kmod-nft-nat kmod-nft-offload kmod-nls-base kmod-oid-registry kmod-phy-aquantia kmod-ppp kmod-pppoe kmod-pppox kmod-qca-nss-dp kmod-qca-ssdk kmod-qrtr kmod-qrtr-smd kmod-random-core kmod-scsi-core kmod-slhc kmod-thermal kmod-tpm kmod-udptunnel4 kmod-udptunnel6 kmod-usb-core kmod-usb-dwc3 kmod-usb-dwc3-qcom kmod-usb-storage kmod-usb-storage-extras kmod-usb-storage-uas kmod-usb-xhci-hcd kmod-usb3 kmod-veth kmod-vxlan libattr libblkid libblobmsg-json libcap libcomerr libdevmapper libevdev libext2fs libfdisk libgmp libiptext libiptext-nft libiptext6 libiwinfo libiwinfo-data libjson-c libjson-script libltdl liblua liblucihttp liblucihttp-lua liblucihttp-ucode liblzo libmbedtls libmnl libmount libncurses libnetfilter-conntrack libnettle libnfnetlink libnftnl libnl-tiny libopenssl libparted libreadline librrd1 libseccomp libsmartcols libss libubox libubus libubus-lua libuci libuclient libucode libudev-zero libusb-1.0 libustream-mbedtls libuuid libuv libwebsockets-full libxtables logd lsblk lua luci luci-app-dockerman luci-app-firewall luci-app-opkg luci-app-statistics luci-app-ttyd luci-base luci-compat luci-lib-base luci-lib-docker luci-lib-ip luci-lib-jsonc luci-lib-nixio luci-light luci-lua-runtime luci-mod-admin-full luci-mod-network luci-mod-status luci-mod-system luci-proto-ipv6 luci-proto-ppp luci-theme-bootstrap mount-utils mtd netifd nftables-json ntfs-3g odhcp6c odhcpd-ipv6only openwrt-keyring opkg parted ppp ppp-mod-pppoe procd procd-seccomp procd-ujail rpcd rpcd-mod-file rpcd-mod-iwinfo rpcd-mod-luci rpcd-mod-rrdns rpcd-mod-ucode rrdtool1 runc smartmontools terminfo tini ttyd ubi-utils uboot-envtools ubox ubus ubusd uci uclient-fetch ucode ucode-mod-fs ucode-mod-html ucode-mod-lua ucode-mod-math ucode-mod-ubus ucode-mod-uci uhttpd uhttpd-mod-ubus urandom-seed urngd usbutils usign vsftpd wireless-regdb wpad-basic-mbedtls xtables-nft zlib"
                cd -
                mkdir firmware
                cp openwrt-imagebuilder-qualcommax-ipq807x.Linux-x86_64/bin/targets/qualcommax/ipq807x/* firmware
                tar -cvf firmware.tar firmware

             - name: Upload artifacts
               uses: actions/upload-artifact@v3
               with:
                name: firmware
                path: firmware.tar

    release:
          name: Make a release
          runs-on: ubuntu-latest
          needs: build

          steps:
            - name: Download the image artifacts
              uses: actions/download-artifact@v3
              with:
                name: firmware

            - name: extract artifacts
              run: tar xf firmware.tar

            - name: Set date env variable
              run: echo "NOW=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
                                                                                                                
            - name: Create a release
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                prerelease: false
                title: "Dynalink DL-WRX36 Firmware ${{ env.NOW }}"
                automatic_release_tag: "v1"
                files: firmware/*
